var PC = require('../models/pcs');
var mongoose = require('mongoose');
mongoose.connect('mongodb://admin:admin@ds111370.mlab.com:11370/ktreeteam');
var pcs = [
    new PC({
        "imagepath": "https://i.imgur.com/aSX8Lnl.jpg",
        "model": "PC Dell Vostro 3668-MTI71403",
        "cpu": "Intel® Core™ i7-7700HQ (2.8GHz upto 3.8GHz, 4Cores, 8Threads, 6MB cache, FSB 8GT/s)",
        "ram": "8GB 2133MHz DDR4",
        "storage": "1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "Intel® HD Graphics 4600",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "4xUSB 2.0 / 1xeSata / DVI / Compoment /",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 15300000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/CIqWLEC.jpg",
        "model": "PC Dell Vostro 3250-STI31301",
        "cpu": "Intel® Core™ i3-6100 (3.70 MHz, 4Threads, 3M Cache, FSB 4GT/s)",
        "ram": "4GB DDR3L Bus 1600MHz",
        "storage": "500GB HDD 7200rpm",
        "cdndcd": "",
        "vga": "",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "VGA, HDMI Lan 1G, Wifi, Bluetooth, 4xUSB 2.0, 2xUSB 3.0, 3x SATA, 1x PCI Ex 1X, 1x PCI Ex 16X",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 8500000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/CIqWLEC.jpg",
        "model": "PC Dell Inspiron 3650-MTI33207",
        "cpu": "Intel® Core™ i3-6100 (3.70 MHz, 4Threads, 3M Cache, FSB 4GT/s)",
        "ram": "8GB DDR3L Bus 1600MHz",
        "storage": "1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "VGA, HDMI Lan 1G, Wifi, Bluetooth, 4xUSB 2.0, 2xUSB 3.0, 3x SATA, 1x PCI Ex 1X, 1x PCI Ex 16X",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 9300000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/bdBPmmF.jpg",
        "model": "PC Dell Vostro 3650MT-PYYPD3",
        "cpu": "Intel® Core™ i5-6400 (2.7GHz upto 3.30 GHz, 4Cores, 4Threads, 6MB Cache, FSB 8GT/s)",
        "ram": "4GB DDR3L Bus 1600MHz",
        "storage": "1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "AMD Radeon R9 360 2GB GDDR5",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "4xUSB 2.0 / 1xeSata / DVI / Compoment /",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 13700000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/7ea37rM.jpg",
        "model": "PC Dell Inspiron 3650-MTI33227",
        "cpu": "Intel® Core™ i3-6100 (3.70 MHz, 4Threads, 3M Cache, FSB 4GT/s)",
        "ram": "8GB DDR3L Bus 1600MHz",
        "storage": "1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "NVidia GTX 705 2GB + Intel® HD Graphics 530",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "VGA, HDMI Lan 1G, Wifi, Bluetooth, 4xUSB 2.0, 2xUSB 3.0, 3x SATA, 1x PCI Ex 1X, 1x PCI Ex 16X",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 10100000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/PMKRM7t.jpg",
        "model": "PC Dell Inspiron 3650-MTI70123R",
        "cpu": "Intel® Core™ i7-6700 (3.4GHz upto 4.0GHz, 4Cores, 8Threads, 8MB cache, FSB 8GT/s)",
        "ram": "16GB DDR3L 1600MHz (2x8GB)",
        "storage": "2TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "AMD Radeon HD R9 360 2GB GDDR5 + Intel® HD Graphics 530",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "VGA, HDMI Lan 1G, Wifi, Bluetooth, 4xUSB 2.0, 2xUSB 3.0, 3x SATA, 1x PCI Ex 1X, 1x PCI Ex 16X",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 19300000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/lXR0FrY.jpg",
        "model": "PC Dell Inspiron 3250SFF-STI51315-8G-1TB-2G",
        "cpu": "Intel® Core™ i5-6400 (2.7GHz upto 3.30 GHz, 4Cores, 4Threads, 6MB Cache, FSB 8GT/s)",
        "ram": "8GB Bus 1600 MHz DDR3L",
        "storage": "1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "NVidia GTX 705 2GB + Intel® HD Graphics 530",
        "monitor": "None",
        "connection": "Lan Gigabit 1000Mb.",
        "tech": "VGA, HDMI Lan 1G, Wifi, Bluetooth, 4xUSB 2.0, 2xUSB 3.0, 3x SATA, 1x PCI Ex 1X, 1x PCI Ex 16X",
        "weight": "None",
        "battery": "None",
        "os": "FreeDos",
        "price": 12600000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/9LHWEf7.jpg",
        "model": "MSI Vortex G65VR 6RD",
        "cpu": "Intel® Core™ i7-6700 (3.4GHz upto 4.0GHz, 4Cores, 8Threads, 8MB cache, FSB 8GT/s)",
        "ram": "16GB DDR4 2133MHz (2*8GB), 4 Slot Ram, Max 64GB.",
        "storage": "256GB SSD PCIe (Super Raid 4) + 1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "NVIDIA GeForce® GTX 1060 6GB GDDR5 + Intel HD Graphic 530",
        "monitor": "None",
        "connection": "Killer N1535 Combo (2*2 a/c) | BT4.1 M.2 type",
        "tech": "Reader SD | Camera HD | HDMI | USB 3.0 | USB C+ | Thunderbolt.",
        "weight": "update",
        "battery": "None",
        "os": "Windows 10 bản quyền",
        "price": 60490000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/9LHWEf7.jpg",
        "model": "MSI Vortex G65VR 6RE",
        "cpu": "Intel® Core™ i7-6700 (3.4GHz upto 4.0GHz, 4Cores, 8Threads, 8MB cache, FSB 8GT/s)",
        "ram": "16GB DDR4 2133MHz (2*8GB), 4 Slot Ram, Max 64GB.",
        "storage": "256GB SSD PCIe (Super Raid 4) + 1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "NVIDIA GeForce® GTX 1070 8GB GDDR5 + Intel HD Graphic 530",
        "monitor": "None",
        "connection": "Killer N1535 Combo (2*2 a/c) | BT4.1 M.2 type",
        "tech": "Reader SD | Camera HD | HDMI | USB 3.0 | USB C+ | Thunderbolt.",
        "weight": "update",
        "battery": "None",
        "os": "Windows 10 bản quyền",
        "price": 64990000,
    }),
    new PC({
        "imagepath": "https://i.imgur.com/9LHWEf7.jpg",
        "model": "MSI Vortex G65VR 6RE SLI",
        "cpu": "Intel® Core™ i7-6700K (4.0GHz upto 4.2GHz, 8Thread, 8M cache, BUS 2133MHz)",
        "ram": "32GB DDR4 2133MHz (2*16GB). Max 64GB",
        "storage": "256GB SSD PCIe (Super Raid 4) + 1TB HDD 7200rpm",
        "cdndcd": "",
        "vga": "NVIDIA GeForce® GTX 1070 SLI 8GB GDDR5 + Intel HD Graphic 530",
        "monitor": "None",
        "connection": "Killer N1535 Combo (2*2 a/c) | BT4.1 M.2 type",
        "tech": "Reader SD | Camera HD | HDMI | USB 3.0 | USB C+ | Thunderbolt.",
        "weight": "update",
        "battery": "None",
        "os": "Windows 10 bản quyền",
        "price": 89600000,
    }),
];

var done = 0;
for (var i = 0; i < pcs.length; i++) {
    pcs[i].save(function(err, result) {
        done++;
        if (err) {
            console.log(err.message);
        }
        if (done === pcs.length) {
            mongoose.disconnect();
        }
    });
}
